[package]
name = "absurdle-fe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = "0.3.0"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
reqwasm = "0.5"
